# Generated by Django 4.1.3 on 2023-02-12 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("checkout_request_id", models.CharField(max_length=255)),
                ("merchant_request_id", models.CharField(max_length=255)),
                ("mpesa_receipt_no", models.CharField(max_length=255)),
            ],
        ),
    ]
