# Generated by Django 3.2.6 on 2023-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee'), ('cashier', 'employee')], default='employee', max_length=255),
        ),
    ]
