# Generated by Django 3.2.6 on 2023-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('cashier', 'cashier')], default='employee', max_length=255),
        ),
    ]
