# Generated by Django 3.2.6 on 2023-02-06 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], max_length=255)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
