# Generated by Django 4.1.3 on 2023-02-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0005_auto_20230206_1447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationstatus",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notify.notification",
            ),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="status",
            field=models.CharField(
                choices=[("read", "read"), ("unread", "unread")],
                default="unread",
                max_length=255,
            ),
        ),
    ]
