# Generated by Django 4.1.3 on 2023-02-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0006_alter_notificationstatus_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("customer", "customer"),
                    ("cashier", "cashier"),
                ],
                default="customer",
                max_length=255,
            ),
        ),
    ]
